---
abstract: 'Real-time web framework'
author:
  - 'Sebastian Riedel <sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious
no_index:
  directory:
    - t
    - inc
    - t
requires:
  perl: '5.010001'
resources:
  MailingList: http://groups.google.com/group/mojolicious
  bugtracker: http://github.com/kraih/mojo/issues
  homepage: http://mojolicio.us
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/kraih/mojo
version: '4.83'
